_target_  : utils.setattrs_kwargs
target  :
  _target_  : learn_koopman_eig.partialised_RBF_maker
  in_features_dim : ${dynamics.dim}
  num_kernels : 2000
  out_features_dim : 1
  normalization : false
#  normalization : true
  reset_params  :
    upper_bound_kernels: 2
    std_shapes: 4

param_specific_hyperparams:
  - params:
      - weights
    weight_decay: 5e-3
  - params:
      - kernels_centers
      - log_shapes
    weight_decay: 0
name  : RBF_kernels${.target.num_kernels}