defaults:
  - main
  - _self_

dynamics_choice : 2bitflipflop_3D

device  : cuda:0

separatrix_locator :
  num_models  : 2

separatrix_locator_fit_kwargs:
  num_epochs: 1000 #10000 #5000 #1000 #500 #1000 #1000 #2000 #200 #500 #5000 #1000 #1000 #10000 #1000 #500 #500 #1000 #500 #1000 #500 #100 #500 #500 #500 # 1000 #1000 #2000 #500 #500 #1000 #400 #1000 #5000 #5000 #3000 #5000 #10000 #5000 #20000 #2000 #500 #2000 #2000 #2000 #1000 #2000 #500 #500 #500 #1000 #1500 #400 #200 #1000 #200 #2000 #400 #2000 #00 #2000 #500 #200 #2000 #0 #2000
  batch_size: 1000
#  batch_size: 5000