function :
  _target_  : dynamical_functions.bistable_ND
  _partial_ : true
  dim       : ${..dim}
  pos       : ${..bistable_axis}

#######

IC_distribution_fit :
  - ${..IC_distribution}
#  - ${..IC_interpolation_line}

#######

IC_distribution:
  _target_  : custom_distributions.makeIIDMultiVariate
  dist  :
    _target_  : torch.distributions.Normal
    loc       : 0
    scale     : 2
  dim : ${..dim}
dist_requires_dim : false

IC_interpolation_line:
  _target_  : custom_distributions.singlePC_distribution_from_hidden
  hidden    : ${..hidden_axis}
  component_id  : 0
  squeeze_first_two_dims  : false
  multiply_scale : 1.0  #0.5

hidden_axis:
  _target_  : custom_distributions.get_stacked_one_hot
  pos       : ${..bistable_axis}
  length    : ${..dim}

name : bistable${.dim}D
dim  : 10 #200 #200 #20 #600 #200 # 600
bistable_axis : 0 #15 #123
equation_latex  : x-x^3
analytical_eigenfunction:
  _target_: dynamical_functions.bistable_ND_koopman_eigenfunction
  _partial_ : true
  dim       : ${..dim}
  pos       : ${..bistable_axis}