function :
  _target_  : dynamical_functions.bistable_ND
  _partial_ : true
  dim       : ${..dim}
  pos       : ${..bistable_axis}

#######

IC_distribution_fit :
#  - ${..IC_distribution}
  - ${..IC_distribution_twentieth}
  - ${..IC_distribution_tenth}
  - ${..IC_distribution_fourth}
  - ${..IC_distribution_half}
  - ${..IC_distribution1}
#  - ${..IC_distribution2}
  - ${..IC_distribution3}
#  - ${..IC_distribution4}
#  - ${..IC_distribution5}
#  - ${..IC_distribution6}
#  - ${..IC_interpolation_line}

#######

IC_distribution:
  _target_  : custom_distributions.makeIIDMultiVariate
  dist  :
#    _target_  : torch.distributions.Normal
#    loc       : 0
#    scale     : 4
    _target_  : torch.distributions.Uniform
    low       : -10
    high      : 10
  dim : ${..dim}

IC_distribution_twentieth:
  _target_  : custom_distributions.makeIIDMultiVariate
  dist  :
    _target_  : torch.distributions.Normal
    loc       : 0
    scale     : 0.05
  dim : ${..dim}

IC_distribution_tenth:
  _target_  : custom_distributions.makeIIDMultiVariate
  dist  :
    _target_  : torch.distributions.Normal
    loc       : 0
    scale     : 0.1
  dim : ${..dim}

IC_distribution_fourth:
  _target_  : custom_distributions.makeIIDMultiVariate
  dist  :
    _target_  : torch.distributions.Normal
    loc       : 0
    scale     : 0.25
  dim : ${..dim}

IC_distribution_half:
  _target_  : custom_distributions.makeIIDMultiVariate
  dist  :
    _target_  : torch.distributions.Normal
    loc       : 0
    scale     : 0.5
  dim : ${..dim}


IC_distribution1:
  _target_  : custom_distributions.makeIIDMultiVariate
  dist  :
    _target_  : torch.distributions.Normal
    loc       : 0
    scale     : 1
  dim : ${..dim}

IC_distribution2:
  _target_  : custom_distributions.makeIIDMultiVariate
  dist  :
    _target_  : torch.distributions.Normal
    loc       : 0
    scale     : 2
  dim : ${..dim}

IC_distribution3:
  _target_  : custom_distributions.makeIIDMultiVariate
  dist  :
    _target_  : torch.distributions.Normal
    loc       : 0
    scale     : 3
  dim : ${..dim}

IC_distribution4:
  _target_  : custom_distributions.makeIIDMultiVariate
  dist  :
    _target_  : torch.distributions.Normal
    loc       : 0
    scale     : 4
  dim : ${..dim}

IC_distribution5:
  _target_  : custom_distributions.makeIIDMultiVariate
  dist  :
    _target_  : torch.distributions.Normal
    loc       : 0
    scale     : 5
  dim : ${..dim}

IC_distribution6:
  _target_  : custom_distributions.makeIIDMultiVariate
  dist  :
    _target_  : torch.distributions.Normal
    loc       : 0
    scale     : 6
  dim : ${..dim}

dist_requires_dim : false

IC_interpolation_line:
  _target_  : custom_distributions.singlePC_distribution_from_hidden
  hidden    : ${..hidden_axis}
  component_id  : 0
  squeeze_first_two_dims  : false
  multiply_scale : 2.0  #0.5

hidden_axis:
  _target_  : custom_distributions.get_stacked_one_hot
  pos       : ${..bistable_axis}
  length    : ${..dim}

name : bistable${.dim}D_multiscale #0.1 #${.IC_distribution.dist.scale}
dim  : 600 #20 #100 #600 #200 #200 #20 #600 #200 # 600
bistable_axis : 0 #15 #123
equation_latex  : x-x^3
analytical_eigenfunction:
  _target_: dynamical_functions.bistable_ND_koopman_eigenfunction
  _partial_ : true
  dim       : ${..dim}
  pos       : ${..bistable_axis}