function :
  _target_  : compose.compose
  _args_    :
    - _target_  : torch.stack
      _partial_ : true
      dim       : -1
    - ${eval:'lambda x:(x[...,1],-x[...,1]+x[...,0]-x[...,0]**3)'}
#    - ${eval:'lambda x:(x[...,1],x[...,0]-x[...,0]**3)'}

IC_distribution:
  _target_  : torch.distributions.Normal
  loc       : 0
  scale     : 2

lims:
  x: [-3,3]
  y: [-3,3]
run_traj: true

name            : duffing
dim  : 2
equation_latex  : y,-y+x-x^3
