function :
  _target_  : compose.compose
  _args_    :
    - _target_  : dynamical_functions.radial_bistable
      _partial_ : true

IC_distribution:
  _target_  : torch.distributions.Normal
  loc       : 0
  scale     : 1
name            : radial2D
dim  : 2
equation_latex  : x-x^3
